/* @flow */

const actionTypes = {
	FETCH_CITY_FULFILLED: 'FETCH_CITY_FULFILLED',
	REMOVE_CITY: 'REMOVE_CITY',
	SUCCESS_SUGGESTS: 'SUCCESS_SUGGESTS',
	SET_KEYWORD: 'SET_KEYWORD',
};

export default actionTypes;
