/* @flow */

const actionTypes = {
	FETCH_CITIES: 'FETCH_CITIES',
	FETCH_CITIES_PENDING: 'FETCH_CITIES_PENDING',
	FETCH_CITIES_FULFILLED: 'FETCH_CITIES_FULFILLED',
	FETCH_CITIES_REJECTED: 'FETCH_CITIES_REJECTED',
	ADD_CITY: 'ADD_CITY',
	ADD_CITY_FULFILLED: 'ADD_CITY_FULFILLED',
	REMOVE_CITY: 'REMOVE_CITY',
	SET_KEYWORD: 'SET_KEYWORD',
};

export default actionTypes;
